use PROJECTO_FASE3
INSERT INTO MONEDA(NOMBRE,SIMBOLO,VALOR) VALUES ('DOLAR','$','8.50');
SELECT*FROM MONEDA

INSERT INTO LISTAPRECIOS(CODIGO,NOMBRE,FECHAINICIO,FECHAFIN) VALUES('1','PRIMERALISTA','4/8/15','5/9/14');
SELECT*FROM LISTAPRECIOS

INSERT INTO PRODUCTO(CODIGOPRODUCTO,NOMBREPRODUCTO)VALUES('1','REGRIGERADORA')
SELECT*FROM PRODUCTO

INSERT INTO DETALLELISTAPRECIOS(VALOR,FKCODIGOPRODUC,FKCODIGOLIST) VALUES ('45','1','1')
SELECT*FROM DETALLELISTAPRECIOS

INSERT INTO CATEGORIA(CODCATEGORIA,NOMBRECATEGORIA) VALUES ('1','MUEBLES')
SELECT*FROM CATEGORIA

INSERT INTO CIUDAD(CODIGOCIUDAD,NOMBRE,CODDEPARTAMENTO) VALUES ('2','GUATEMALA','0')
SELECT*FROM CIUDAD

INSERT INTO DEPARTAMENTO(CODIGODEPARTAMENTO,NOMBRE) VALUES ('0','VENEZUELA')
SELECT*FROM DEPARTAMENTO

INSERT INTO CLIENTE(NITCLIENTE,NOMBRECLIENTE,APELLIDOSCLIENTE,FECHANACIMIENTOCLIENTE,DIRECCIONDOMICILIO,TELEFONO,CELULAR,EMAIL,LIMITECREDITO,DIASCREDITO,CODEPARTAMENTO,CODCIUDAD) 
VALUES ('1234','ALFONZO','GUANCA','8794546','DFDFD','7846511','4564','DFJDKLFD45','4890','1','0','2');
SELECT *FROM CLIENTE

INSERT INTO LISTACLIENTE(FECHAINICIO,FECHAFIN,CODIGOLISTAPRECIOS,NITCLIENTE) VALUES ('8/95/','18/25/','1','1234')
SELECT*FROM LISTACLIENTE

INSERT INTO PUESTO(CODPUESTO,NOMBREPUESTO) VALUES ('1','SUPERVISOR')
SELECT*FROM PUESTO

INSERT INTO EMPLEADO(NITEMPLEADO,NOMBRES,APELLIDOS,FECHANACIMIENTO,DIRECCION,TELEFONODOMICILIO,CELULAR,EMAIL,CODIGOPUESTO)
VALUES ('123','JUA','GONZALES','45464','DDFDDF45D4565','7811545','51651','DJFKD44511111','1')
SELECT*FROM EMPLEADO

INSERT INTO METAS(FECHA,CODIGOEMPELADO) VALUES('4548/78','222000-2')
INSERT INTO DETALLEMPLEADO(VENTAMETA,CODIGOPRODUC,NITEMPLEADO) VALUES ('4567','10101','111000-1')
SELECT EMPLEADO.NITEMPLEADO,EMPLEADO.JEFEEMPLEADO,PUESTO.NOMBREPUESTO,EMPLEADO.NOMBRES FROM EMPLEADO,PUESTO WHERE EMPLEADO.CODIGOPUESTO=PUESTO.CODPUESTO

SELECT*FROM CATEGORIA
SELECT*FROM CIUDAD
SELECT*FROM CLIENTE
SELECT*FROM DEPARTAMENTO
SELECT*FROM DETALLELISTAPRECIOS
SELECT*FROM DETALLEMETA
SELECT*FROM EMPLEADO
SELECT*FROM LISTACLIENTE
SELECT*FROM LISTAPRECIOS
SELECT*FROM METAS
SELECT*FROM MONEDA
SELECT*FROM PRODUCTO
SELECT*FROM PUESTO
SELECT*FROM ORDEN
-----------------------------CIUDADD---------------
DELETE FROM CATEGORIA
DELETE FROM CIUDAD
DELETE FROM CLIENTE
DELETE FROM DEPARTAMENTO
DELETE FROM DETALLELISTAPRECIOS
DELETE FROM DETALLEMETA
DELETE FROM EMPLEADO
DELETE FROM LISTACLIENTE
DELETE FROM LISTAPRECIOS
DELETE FROM METAS
DELETE FROM MONEDA
DELETE FROM PRODUCTO
DELETE FROM PUESTO
DELETE FROM ORDEN
DELETE DETALLEPRODUCTOORDEN

------------------------------------CUIDADO--------------------



SELECT VALOR,NOMBREPRODUCTO,FKCODIGOLIST,PRODUCTO.CODIGOPRODUCTO FROM  DETALLELISTAPRECIOS INNER JOIN PRODUCTO ON DETALLELISTAPRECIOS.FKCODIGOPRODUC=PRODUCTO.CODIGOPRODUCTO WHERE NOMBREPRODUCTO='producto1' AND DETALLELISTAPRECIOS.FKCODIGOLIST='01010'

SELECT LISTAPRECIOS.CODIGO,VALOR 
FROM LISTAPRECIOS INNER JOIN DETALLELISTAPRECIOS 
ON LISTAPRECIOS.FECHAINICIO<'05/01/2014' AND LISTAPRECIOS.FECHAFIN>'05/01/2014'---AND  INNER JOIN PRODUCTO ON DETALLELISTAPRECIOS.FKCODIGOPRODUC=PRODUCTO.CODIGOPRODUCTO
 --ON LISTAPRECIOS.FECHAINICIO<'05/01/2014' AND LISTAPRECIOS.FECHAFIN>'05/01/2014'
SELECT*FROM DETALLELISTAPRECIOS
SELECT*FROM LISTAPRECIOS
SELECT*FROM PRODUCTO


SELECT CODIGOORDEN FROM ORDEN WHERE ESTADOAPROBACION='Procesando' AND SALDOFALTA>'0'

SELECT VALOR,DETALLELISTAPRECIOS.FKCODIGOPRODUC FROM DETALLELISTAPRECIOS INNER JOIN LISTAPRECIOS ON DETALLELISTAPRECIOS.FKCODIGOLIST=LISTAPRECIOS.CODIGO WHERE LISTAPRECIOS.FECHAINICIO<'31/10/2014' AND LISTAPRECIOS.FECHAFIN>'31/10/2014'

SELECT CODIGO,LISTAPRECIOS.FECHAINICIO FROM LISTAPRECIOS WHERE FECHAFIN>'31/10/2014' AND FECHAINICIO<'31/10/2014'
SELECT CODIGO,LISTAPRECIOS.FECHAINICIO FROM LISTAPRECIOS WHERE FECHAFIN>'" + fecha + "' AND FECHAINICIO<'" + fecha + "'




SELECT VALOR,NOMBREPRODUCTO,FKCODIGOLIST,PRODUCTO.CODIGOPRODUCTO FROM DETALLELISTAPRECIOS INNER JOIN PRODUCTO ON DETALLELISTAPRECIOS.FKCODIGOPRODUC=PRODUCTO.CODIGOPRODUCTO WHERE NOMBREPRODUCTO='producto8' AND DETALLELISTAPRECIOS.FKCODIGOLIST='03030'


SELECT NITEMPLEADO FROM EMPLEADO WHERE JEFEEMPLEADO='555000-5'


INSERT INTO ORDEN(CODIGOORDEN,TOTALPAGAR,FECHACREACION,FECHACERRADA,DIASFALTANTE,PAGOABONO,SALDOFALTA,ESTADOAPROBACION,FECHAAPROBACION,DIASFALTANTEAPROBACION,NITEMPLEADOVENDE,NITCLIENTE)
VALUES ('4','150','154/4545','1215/7878','5','500','0','Aprobada','8/182','9','444000-4','111111-1')

SELECT CODIGOORDEN FROM ORDEN WHERE NITEMPLEADOVENDE='555000-5'

SELECT * FROM EMPLEADO
SELECT CODIGOORDEN FROM ORDEN INNER JOIN EMPLEADO ON NITEMPLEADOVENDE=EMPLEADO.NITEMPLEADO WHERE JEFEEMPLEADO='111000-1' AND ORDEN.ESTADOAPROBACION='Procesando' AND ORDEN.SALDOFALTA>0
SELECT*FROM ORDEN

SELECT *FROM ORDEN WHERE (SALDOFALTA>0) AND (NITCLIENTE='111111-1')


SELECT*FROM ORDEN
SELECT *FROM DETALLEPRODUCTOORDEN

INSERT INTO DETALLEPRODUCTOORDEN(NOMBREPRODUCTO,CANTIDAD,VALOR,CODIGOORDEN, CODIGOPRODUCTO) VALUES ('producto4',125,456,'1','40404')

SELECT LISTAPRECIOS.NOMBRE,LISTAPRECIOS.FECHAINICIO FROM LISTAPRECIOS INNER JOIN LISTACLIENTE ON LISTACLIENTE.CODIGOLISTAPRECIOS=LISTAPRECIOS.CODIGO WHERE LISTACLIENTE.NITCLIENTE='555555-5' 

SELECT VALOR FROM DETALLELISTAPRECIOS INNER JOIN LISTAPRECIOS ON( DETALLELISTAPRECIOS.FKCODIGOLIST=LISTAPRECIOS.CODIGO) INNER JOIN PRODUCTOS WHERE LISTAPRECIOS.FECHAINICIO<'05/01/2012' AND LISTAPRECIOS.FECHAFIN>'05/01/2012'

SELECT LISTAPRECIOS.FECHAINICIO FROM LISTAPRECIOS  WHERE LISTAPRECIOS.NOMBRE='Segundo Semestre 2014'

SELECT LISTAPRECIOS.FECHAFIN FROM LISTAPRECIOS WHERE LISTAPRECIOS.NOMBRE='" + nombre + "';
SELECT LISTAPRECIOS.FECHAFIN FROM LISTAPRECIOS WHERE LISTAPRECIOS.NOMBRE='Segundo Semestre 2014' 
SELECT LISTAPRECIOS.NOMBRE FROM LISTACLIENTE INNER JOIN LISTAPRECIOS ON (LISTACLIENTE.CODIGOLISTAPRECIOS=LISTAPRECIOS.CODIGO) WHERE LISTACLIENTE.NITCLIENTE='777777-7';

SELECT*FROM LISTACLIENTE
SELECT*FROM LISTAPRECIOS
SELECT*FROM DETALLELISTAPRECIOS
SELECT*FROM PRODUCTO

---DATE CAST('4/8/2014')

SELECT PRODUCTO.NOMBREPRODUCTO FROM PRODUCTO INNER JOIN DETALLELISTAPRECIOS ON PRODUCTO.CODIGOPRODUCTO=DETALLELISTAPRECIOS.FKCODIGOPRODUC INNER JOIN LISTAPRECIOS ON DETALLELISTAPRECIOS.FKCODIGOLIST=LISTAPRECIOS.CODIGO WHERE LISTAPRECIOS.NOMBRE='Segundo Semestre 2014'

--------------------------actualizaciones
UPDATE ORDEN SET ORDEN.TOTALPAGAR =50000 ,ORDEN.SALDOFALTA=50000 WHERE ORDEN.CODIGOORDEN='1';


SELECT        IDDETALLE, NOMBREPRODUCTO, CANTIDAD, VALOR
FROM            DETALLEPRODUCTOORDEN INNER JOIN ORDEN ON DETALLEPRODUCTOORDEN.CODIGOORDEN=ORDEN.CODIGOORDEN
WHERE        (DETALLEPRODUCTOORDEN.CODIGOORDEN LIKE '1')AND (ORDEN.ESTADOAPROBACION = 'Procesando')

SELECT*FROM ORDEN
SELECT *FROM DETALLEPRODUCTOORDEN

SELECT CODIGOORDEN FROM ORDEN WHERE ESTADOAPROBACION='Cerrada' AND SALDOFALTA>'0'





UPDATE CLIENTE SET CLIENTE.LIMITECREDITO = '30000.00',CLIENTE.CANTIDADORDENES='NULL' WHERE NITCLIENTE='333333-3'
UPDATE CLIENTE SET CLIENTE.LIMITECREDITO = ' ',CLIENTE.CANTIDADORDENES=" + cantidadOrden +  " WHERE NITCLIENTE='" + NitCliente + "'

SELECT*FROM CLIENTE
SELECT*FROM ORDEN
SELECT *FROM DETALLEPRODUCTOORDEN

DELETE DETALLEPRODUCTOORDEN WHERE CODIGOPRODUCTO='60606' AND CODIGOORDEN='1' AND CANTIDAD='3'
 
 SELECT NITCLIENTE,NOMBRECLIENTE,APELLIDOSCLIENTE,CANTIDADORDENES,LIMITECREDITO,DIASCREDITO ,CLIENTE.DIRECCIONDOMICILIO FROM CLIENTE WHERE NITCLIENTE='222222-2';

 SELECT CODIGOORDEN FROM ORDEN WHERE NITEMPLEADOVENDE='555000-5' AND ESTADOAPROBACION='Procesando' AND SALDOFALTA>0

 SELECT TOTALPAGAR FROM ORDEN WHERE ORDEN.CODIGOORDEN='3'

 SELECT CLIENTE.LIMITECREDITO FROM CLIENTE INNER JOIN ORDEN ON ORDEN.NITCLIENTE=CLIENTE.NITCLIENTE WHERE ORDEN.CODIGOORDEN='7'
 SELECT*FROM CLIENTE
SELECT*FROM ORDEN

UPDATE ORDEN SET FECHACERRADA='',ESTADOAPROBACION='Cerrada',PAGOABONO='Pendiente de Pago' WHERE CODIGOORDEN='1'


SELECT CODIGOORDEN FROM ORDEN WHERE ESTADOAPROBACION='Procesando' AND SALDOFALTA>0

UPDATE ORDEN SET ESTADOAPROBACION='Procesando',FECHAAPROBACION='',DIASFALTANTEAPROBACION='',EMPLEADOAPROBACION='' WHERE CODIGOORDEN='1'

select*from EMPLEADO
SELECT CODIGOORDEN FROM ORDEN INNER JOIN EMPLEADO ON NITEMPLEADOVENDE=EMPLEADO.NITEMPLEADO WHERE (EMPLEADO.JEFEEMPLEADO='222000-2'OR ORDEN.NITEMPLEADOVENDE='222000-2') AND ORDEN.ESTADOAPROBACION='Cerrada' AND ORDEN.SALDOFALTA>0 

SELECT CODIGOORDEN FROM ORDEN WHERE ORDEN.PAGOABONO='Pendiente de Pago'
SELECT CODIGOORDEN FROM ORDEN WHERE ORDEN.PAGOABONO='Pendiente de Pago' and ORDEN.NITEMPLEADOVENDE='444000-4' ;
SELECT CODIGOORDEN FROM ORDEN INNER JOIN EMPLEADO ON ORDEN.NITEMPLEADOVENDE=EMPLEADO.NITEMPLEADO WHERE (EMPLEADO.JEFEEMPLEADO='333000-3' OR ORDEN.NITEMPLEADOVENDE='333000-3') AND ORDEN.PAGOABONO='Pendiente de Pago'
SELECT*FROM ORDEN


SELECT CODIGOORDEN FROM ORDEN WHERE ESTADOAPROBACION='Aprobado' AND PAGOABONO='Pendiente de Pago' AND SALDOFALTA>0
SELECT*FROM MONEDA

SELECT ORDEN.NITCLIENTE,CLIENTE.NOMBRECLIENTE,CLIENTE.APELLIDOSCLIENTE,CLIENTE.DIRECCIONDOMICILIO,CLIENTE.TELEFONO FROM ORDEN INNER JOIN CLIENTE ON CLIENTE.NITCLIENTE=ORDEN.NITCLIENTE WHERE ORDEN.CODIGOORDEN='1'

 SELECT*FROM CLIENTE

 SELECT ORDEN.TOTALPAGAR,ORDEN.FECHACREACION,ORDEN.FECHACERRADA,ORDEN.FECHAAPROBACION,EMPLEADO.NOMBRES,PUESTO.NOMBREPUESTO 
 FROM ORDEN INNER JOIN EMPLEADO ON ORDEN.EMPLEADOAPROBACION=EMPLEADO.NITEMPLEADO 
 INNER JOIN PUESTO ON EMPLEADO.CODIGOPUESTO=PUESTO.CODPUESTO
 WHERE ORDEN.CODIGOORDEN='1'
SELECT*FROM ORDEN
SELECT*FROM EMPLEADO


SELECT LISTACLIENTE.CODIGOLISTAPRECIOS,LISTAPRECIOS.NOMBRE FROM LISTACLIENTE INNER JOIN LISTAPRECIOS ON LISTACLIENTE.CODIGOLISTAPRECIOS=LISTAPRECIOS.CODIGO WHERE LISTACLIENTE.NITCLIENTE='222222-2'  AND CAST( LISTACLIENTE.FECHAINICIO AS datetime2)<= CAST( '02/11/2014' as datetime2) 
AND CAST( LISTACLIENTE.FECHAFIN AS smalldatetime)= CAST( '02/11/2014' AS smalldatetime) 
						30/04/2014	
						01/01/2014																																																					 
SELECT*FROM LISTACLIENTE
SELECT*FROM LISTAPRECIOS
SELECT*FROM DETALLELISTAPRECIOS
select*from CLIENTE

select CODIGOPRODUCTO,NOMBREPRODUCTO,VALOR,CANTIDAD from DETALLEPRODUCTOORDEN where CODIGOORDEN='1' order by NOMBREPRODUCTO

select*from MONEDA

select VENTAMETA from DETALLEMETA inner join METAS on detallemeta.codigometa=METAS.IDMETA where METAS.FECHA<='09/2014' and METAS.CODIGOEMPELADO='444000-4'

select*from METAS
select FECHA from METAS where FECHA<'10/2014'
select IDMETA from METAS where FECHA='10/2014' and CODIGOEMPELADO='444000-4'
select*from ORDEN

select COUNT(ESTADOAPROBACION) from ORDEN where ESTADOAPROBACION='Cerrada' and ORDEN.NITEMPLEADOVENDE='111000-1'

select idmeta from METAS where Metas.FECHA='10/2014' and METAS.CODIGOEMPELADO='444000-4'
select*from PRODUCTO
select*from CATEGORIA
select *from DETALLEMETA
select*from METAS

select NOMBRECATEGORIA,IDMETA from CATEGORIA inner join PRODUCTO on CATEGORIA.CODCATEGORIA=PRODUCTO.CATEGORIA inner join detallemeta on PRODUCTO.CODIGOPRODUCTO=detallemeta.codigoproduc inner join METAS on detallemeta.codigometa=METAS.IDMETA where METAS.FECHA='10/2014' and METAS.CODIGOEMPELADO='444000-4'
select NOMBRECATEGORIA,IDMETA from METAS inner join detallemeta on detallemeta.codigometa=METAS.IDMETA inner join PRODUCTO on PRODUCTO.CODIGOPRODUCTO=detallemeta.codigoproduc inner join CATEGORIA on  CATEGORIA.CODCATEGORIA=PRODUCTO.CATEGORIA where METAS.FECHA='10/2014' and METAS.CODIGOEMPELADO='444000-4'

select NOMBRECATEGORIA from CATEGORIA inner join PRODUCTO on CATEGORIA.CODCATEGORIA=PRODUCTO.CATEGORIA


select*from pago
insert into PAGO(CODIG)





























